apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: ems
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: nguyenducmanh247/ems-analytics:latest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/ems-analytics"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ems-secrets
                  key: jwt-secret
            - name: DATA_COLLECTION_URL
              value: "http://data-collection:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: ems
spec:
  type: ClusterIP
  selector:
    app: analytics
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002

