apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collection
  namespace: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collection
  template:
    metadata:
      labels:
        app: data-collection
    spec:
      containers:
        - name: data-collection
          image: nguyenducmanh247/ems-data-collection:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/ems-data-collection"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: data-collection
  namespace: ems
spec:
  type: ClusterIP
  selector:
    app: data-collection
  ports:
  - protocol: TCP  
    port: 5000
    targetPort: 5000
