apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collection
  namespace: ems
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-collection
  template:
    metadata:
      labels:
        app: data-collection
    spec:
      containers:
      - name: data-collection
        image: ${DOCKER_REGISTRY}/ems-data-collection:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/ems-data-collection"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
