apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-control
  namespace: ems
spec:
  replicas: 2
  selector:
    matchLabels:
      app: device-control
  template:
    metadata:
      labels:
        app: device-control
    spec:
      containers:
        - name: device-control
          image: nguyenducmanh247/ems-device-control:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/ems-device-control"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ems-secrets
                  key: jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: device-control
  namespace: ems
spec:
  type: ClusterIP
  selector:
    app: device-control
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
