apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-control
  namespace: ems
spec:
  replicas: 2
  selector:
    matchLabels:
      app: device-control
  template:
    metadata:
      labels:
        app: device-control
    spec:
      containers:
      - name: device-control
        image: nguyenducmanh247/energy-device-control:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/ems-device-control"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ems-secrets
              key: jwt-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
