apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-control
  namespace: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-control
  template:
    metadata:
      labels:
        app: device-control
    spec:
      containers:
        - name: device-control
          image: nguyenducmanh247/ems-device-control:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3001"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/ems-device-control"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ems-secrets
                  key: jwt-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: device-control
  namespace: ems
spec:
  type: ClusterIP
  selector:
    app: device-control
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
