apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ems
spec:
  selector:
    app: gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: LoadBalancer
