apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 256Mi       
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
      

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ems
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - protocol: TCP 
    port: 27017
    targetPort: 27017
