apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-service
  namespace: ems
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb-service
  template:
    metadata:
      labels:
        app: mongodb-service
    spec:
      containers:
        - name: mongodb-service
          image: nguyenducmanh247/ems-mongodb:latest
          ports:
            - containerPort: 3010
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3010"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/ems"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ems-secrets
                  key: jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: ems
spec:
  type: ClusterIP
  selector:
    app: mongodb-service
  ports:
  - protocol: TCP
    port: 3010
    targetPort: 3010
