apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: ems
data:
  redis.conf: |
    maxmemory 100mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
