apiVersion: v1
kind: Secret
metadata:
  name: ems-secrets
  namespace: ems
type: Opaque
data:
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2hlcmU= # your_jwt_secret_here
  smtp-host: c210cC5leGFtcGxlLmNvbQ== # smtp.example.com
  smtp-port: NTg3 # 587
  smtp-user: dXNlckBleGFtcGxlLmNvbQ== # user@example.com
  smtp-pass: eW91cl9zbXRwX3Bhc3N3b3Jk # your_smtp_password
