apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  namespace: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
        - name: ui-service
          image: nguyenducmanh247/ems-ui-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: API_GATEWAY_URL
              value: "http://gateway:80"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ems-secrets
                  key: jwt-secret

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: ems
spec:
  type: ClusterIP
  selector:
    app: ui-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000